version: "3.9"
services:
  k6:
    image: loadimpact/k6:latest
    depends_on:
      - web
    command: run /test/test.js
    volumes:
      - ./test:/test
    networks:
      - monitoring
      - app
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
  web:
    image: containous/whoami
    container_name: whoami
    hostname: whoami
    ports:
      - 3001:80
    networks:
      - app
  influxdb:
    image: influxdb:1.8
    restart: always
    networks:
      - monitoring
    environment:
      - INFLUXDB_DB=k6
  grafana:
    image: grafana/grafana
    depends_on:
      - influxdb
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - monitoring
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,\
                           grafana-influxdb-08-datasource,\
                           grafana-kairosdb-datasource,\
                           grafana-piechart-panel,\
                           grafana-simple-json-datasource,\
                           grafana-worldmap-panel"
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
networks:
  monitoring:
  app:
